---
- hosts: all
  tasks:

    - name: install packages
      apt:
        name: ['python3', 'python3-pip', 'python3-psycopg2', 'python3-django']
        update_cache: true
      become: true

    - name: copy blank file
      copy:
        src:  ../blankfile
        dest: /tmp/blankfile