Vagrant.configure("2") do |config|
    config.vm.hostname    = "ubuntu-test-env"
    config.vm.box         = "capensis/ubuntu18.04"
    config.vm.box_version = "0.1"
    config.vm.provider "lxc" do |lxc|
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose  = "true"
    end
  end